version: 2
updates:
- package-ecosystem: npm
  directory: "/"
  schedule:
    interval: daily
    time: "03:00"
  open-pull-requests-limit: 10
  ignore:
  - dependency-name: "@types/node"
    versions:
    - 14.14.24
    - 14.14.32
    - 15.0.0
  - dependency-name: "@types/react"
    versions:
    - 17.0.4
  - dependency-name: next
    versions:
    - 10.0.9
