dist_path: './dist'
content_path: './content/'
static_source_path: './public/'
static_files_extensions:
- css
- js
- png
- jpg
- jpeg
- gif
- svg
- webmanifest
- ico
- txt
- html
- ttf
- mjs
static_path: './public/'
template: '../hamon/'
domain: 'https://barhamon.com'
title: 'Serhiy Barhamon'
description: 'blog'
template_config:
  index_tags:
    - life
    - music
    - books
    - software
    - adventures
  index_article_id: '/me'
  footer:
    social:
      github: 'https://github.com/Lurk'
      mastodon: 'https://mas.to/@barhamon'
      facebook: 'https://www.facebook.com/bargamon/'
      instagram: 'https://www.instagram.com/fedorpupkin/'
yamd_processors:
  convert_cloudinary_embed: true
  generate_alt_text:
    prompt: 'Describe image in one sentence. Be precise.'
    temperature: 0.1
