dist_path: './dist'
content_path: './content/'
static_source_path: './public/'
static_files_extensions:
- css
- js
- png
- jpg
- jpeg
- gif
- svg
- webmanifest
- ico
- txt
- html
- ttf
static_path: './public/'
template: '../hamon/'
domain: 'https://barhamon.com'
title: 'Serhiy Barhamon'
description: 'blog'
template_config:
  index_tags:
    - music
    - software
    - adventures
    - life
    - books
  should_unpack_cloudinary: true
  index_post: '/me.html'

