dist_path: './dist'
content_path: './content/'
static_source_path: './public/'
static_path: './public/'
template: '../hamon/'
domain: 'https://barhamon.com'
title: 'Serhiy Barhamon blog'
description: 'blog'
template_config:
  index_tags:
    - adventures
    - life
    - books
    - software
    - music
  should_unpack_cloudinary: true
  index_post: '/me.html'

