dist_path: './dist'
content_path: './content/'
static_source_path: './public/'
static_files_extensions:
- css
- js
- png
- jpg
- jpeg
- gif
- svg
- webmanifest
- ico
- txt
- html
- ttf
- mjs
static_path: './public/'
template: '../hamon/'
domain: 'https://barhamon.com'
title: 'Serhiy Barhamon'
description: 'blog'
template_config:
  index_tags:
    - adventures
    - life
    - software
    - books
    - music
  index_article_id: '/me'
yamd_processors:
  convert_cloudinary_embed: true
  generate_alt_text:
    prompt: 'Describe image in one sentence. Be precise.'
    temperature: 0.1
