name: test
on:
  push:
  pull_request:
    branches: [ master ]

  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2        
      - name: Setup Node.js environment
        uses: actions/setup-node@v2.1.2
      - name: Install modules
        run: npm install
      - name: Run tests
        run: npm run test:ci
      
      
